In [1]:
import pandas as pd
import numpy as np

# No modifications can be made without a selected code snippet.import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("Banco de dados.xlsx")
df = df[df['Área colhida'] != '...']
df1 = pd.read_excel("fator de transformação.xlsx")

In [3]:
df["Cultura"].unique()

array(['Abacate', 'Abacaxi*', 'Açaí', 'Algodão', 'Amendoim', 'Arroz',
       'Banana', 'Batata-doce', 'Batata-inglesa ', 'Cana de açúcar',
       'Castanha de caju', 'Coco com casca', 'Fava (em grão)', 'Feijão ',
       'Goiaba', 'Laranja', 'Limão', 'Mamão', 'Mandioca', 'Manga',
       'Maracujá', 'Melancia', 'Melão', 'Milho', 'Pimenta-do-reino',
       'Soja (em grão)', 'Tangerina', 'Tomate', 'Alho',
       'Cacau (em amêndoa)', 'Café', 'Caqui', 'Cebola',
       'Dendê (cacho de coco)', 'Guaraná (semente)', 'Mamona (baga)',
       'Marmelo', 'Palmito', 'Sisal ou agave (fibra)', 'Sorgo', 'Trigo ',
       'Urucum (semente)', 'Uva', 'Figo'], dtype=object)

In [4]:
df = df[df['Cultura'].isin(df1['Cultura'])]
df

                    Municípios Área colhida Produção    Cultura
77            Água Branca (AL)            6        3    Algodão
78                 Anadia (AL)          500     1750    Algodão
79            Mata Grande (AL)           10        5    Algodão
80              Pariconha (AL)           15        7    Algodão
81                 Penedo (AL)           90       70    Algodão
...                        ...          ...      ...        ...
16235        Itabaianinha (SE)           24      288  Tangerina
16236  Itaporanga d'Ajuda (SE)            4       56  Tangerina
16237             Lagarto (SE)            8       80  Tangerina
16238           Pedrinhas (SE)            8      104  Tangerina
16239             Umbaúba (SE)           90     1350  Tangerina

[8822 rows x 4 columns]

In [ ]:
# Quantificação utilizando simulação de monte Carlo

resultados = []

for municipio in df['Municípios'].unique():
    df_producao_municipio = df[df['Municípios'] == municipio]

    residuos_simulados = []
    biochar_simulado = []
    sequestro_carbono_simulado = []

    # Iterar sobre as culturas do município atual
    for cultura in df['Cultura']:
        df_coeficientes_cultura = df1[df1['Cultura'] == cultura]
        producao = df[df['Cultura'] == cultura]['Produção'].values[0]

        # Simular a produção com desvio padrão de 20% da média
        producao_simulada = np.random.normal(producao, 0.2 * producao, 10000)
        # Simular o rendimento do biochar (25%) com desvio padrão de 5%
        rendimento_biochar_simulado = np.random.normal(0.25, 0.05 * 0.25, 10000)
        # Simular o conteúdo de carbono do biochar (BCC) com desvio padrão de 10%
        bcc_simulado = np.random.normal(df1['BCC'].mean(), 0.1 * df1['BCC'].mean(), 10000)

        # Iterar sobre os tipos de coeficientes da cultura atual
        for index, coef in df_coeficientes_cultura.iterrows():
            for producao, rendimento_biochar, bcc, area_colhida in zip(producao_simulada, rendimento_biochar_simulado, bcc_simulado, df['Área colhida']):
              
                # Cálculo dos resíduos e do biochar usando RPR e produção simulada
                if not pd.isna(coef['RPR']):
        
                    residuos = coef['RPR'] * coef['CF'] * (1 - coef['MC']) * producao
                    biochar = residuos * rendimento_biochar
                    sequestro_carbono = biochar * bcc

                    residuos_simulados.append(residuos)
                    biochar_simulado.append(biochar)
                    sequestro_carbono_simulado.append(sequestro_carbono)
                    
                # Cálculo dos resíduos e do biochar usando ARP e área colhida
                elif not pd.isna(coef['ARP']):
                
                    residuos = coef['ARP'] * coef['CF'] * (1 - coef['MC']) * area_colhida
                    biochar = residuos * rendimento_biochar
                    sequestro_carbono = biochar * bcc

                
                    residuos_simulados.append(residuos)
                    biochar_simulado.append(biochar)
                    sequestro_carbono_simulado.append(sequestro_carbono)

    # Cálculo dos intervalos de confiança para os resíduos, biochar e sequestro de carbono
    resultados.append({
        'Município': municipio,
        'Soma de Resíduos': np.mean(residuos_simulados),
        'IC Resíduos Inferior': np.percentile(residuos_simulados, 2.5),
        'IC Resíduos Superior': np.percentile(residuos_simulados, 97.5),
        'Biochar Produzido': np.mean(biochar_simulado),
        'IC Biochar Inferior': np.percentile(biochar_simulado, 2.5),
        'IC Biochar Superior': np.percentile(biochar_simulado, 97.5),
        'Sequestro de Carbono (kg)': np.mean(sequestro_carbono_simulado),
        'IC Sequestro Carbono Inferior': np.percentile(sequestro_carbono_simulado, 2.5),
        'IC Sequestro Carbono Superior': np.percentile(sequestro_carbono_simulado, 97.5)
    })

In [1]:
df_resultados = pd.DataFrame(resultados)
display(df_resultados)

NameError: name 'pd' is not defined